---
title: "Summarize data"
format: html
---
# Instructions

This week, you learned about several more pandas methods.

You'll use these skills to compute the average monthly temperatures for each year and visualize the results by year.

To learn more about the variables contained in the data set,
refer to the data dictionary [here](https://rstudio.github.io/academy-python-solar-power/assets/power_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None)
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off
```

## Summarize data

In this milestone, you'll use groupwise summaries to compute average monthly temperatures for each year and plot the results.

## Recreation

### Part 1 - Import

Before you begin, you will need to import the `power_with_months` data set.
Use the code chunk below to read the data from the data file `power_with_months.csv`,
which is stored in the `data/` folder in your working directory.
Be sure to save the data set to a variable named `power`.

```{python}
#| label: 'recreation-import'

```

Then, **run the code chunk below** to convert the `month` and `year` columns into categorical variables before plotting them.
Don't worry about how this code works for now; we'll go over all the details in a future week.

```{python}
#| label: 'prep-categorical'
month_order = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
power['month'] = pd.Categorical(power['month'], categories=month_order, ordered=True)
power['year'] = power['year'].astype('category') # because `year` is numeric, the categories will appear in the desired order
```

### Part 2 - Visualize data

Using the File Explorer on the left, navigate to the `images/` directory, then click on `milestone04a.png` to open an image in the Editor pane

Consider this plot of the temperature, `t2m`, on the first day of each month.
Each line represents a different year.
Your task is to recreate this plot using what you've learned so far with the `power` data set.
For now, don't worry about the overlapping month names.

Use plotnine functions in the chunk below to re-create the plot.

**Hints:**

- Before plotting, you will need to filter down to rows where day (`dd`) is `1`
- Be careful to not overwrite the `power` variable. Instead, save the subset data as `subset`
- Depending on your chosen `geom_`, you may need to specify a `group` aesthetic in addition to the `color` aesthetic

```{python}
#| label: 'recreation-create'

```

### Compute average temperature

Run the code below to compute the average annual temperature for the year 2012.

```{python}
#| label: 'annual-temp'
subset = power.loc[power['year'] == 2012]

subset.t2m.mean()
```

### Part 3 - Summarize data

Now, you'll compute the average _monthly_ temperature for each year.
Run the code below to see a table.

```{python}
#| label: 'recreate-this'
solution = pd.read_csv('data/milestone04.csv')
solution
```

Your task is to use what you've learned about functions and grouped summaries to transform `power` into this table.

You will need to:

1. Group the `power` data
2. Extract the column that you wish to average (`t2m`)
3. Calculate the mean temperature for each group
4. Reset the index
5. Rename the new column `average_temp`

Work in the code chunk below.
Save your result as `average_temps`.

```{python}
#| label: 'recreation-summary'

```

Run the following code chunk to test whether your table matches the solution:

```{python}
#| label: 'compare'

# If your answer is correct, the comparison should return an empty DataFrame.
average_temps.round(10).compare(solution.round(10))
```

### Part 4 - Visualize it again

Using the File Explorer on the left, navigate to the `images/` directory, then click on `milestone04b.png` to open an image in the Editor pane

Finally, update your plot from above with this new data to recreate this plot,
which displays the average monthly temperature for each year.

```{python}
#| label: 'recreation-update'

```

## Extension

Using the code chunk below, investigate a research question about this data, using the data wrangling skills you learned this week. Some ideas:

1. In addition to monthly averages of temperature, calculate and visualize daily and yearly averages. How much variation do you see in temperature within each of these levels of temporal granularity?
2. What temporal patterns do you see in other variables, e.g. surface pressure, wind speed, relative humidity, etc.? Do you notice different temporal variations across these different variables? Does this track with your intuition?
3. [any other research question of interest]

Alternately, working with a data set of your own, complete the following:

1. Read in your data
2. Group your data, perform a summary function on your data, and produce a simple table from some subset of your data
3. Create a related graph of this data subset using plotnine

```{python}
#| label: 'extension'

```
