---
title: "Wrangle rows and columns"
format: html
---
# Instructions

This week, you learned about several more pandas methods and attributes.
These functions help you work with the columns in your data set.

To learn more about the variables contained in the data set, refer to the data dictionary
[here](https://rstudio.github.io/academy-python-solar-power/assets/power_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None)
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off

```

## Wrangle rows and columns

In this milestone, you'll create a new variable that converts relative humidity to percent humidity.
Then, to better visualize the data, you'll plot percent humidity versus temperature.

## Recreation

### Part 1 - Import

Before you begin, you will need to import your data set.
Use the code chunk below to read the data from the data file `power.csv`,
which is stored in the `data/` folder in your working directory.
Be sure to save the data set to a variable named `power`.

```{python}
#| label: 'recreation-import'

```

### Part 2 - Create and Summarize

Run the code below to see a table.

```{python}
#| label: 'recreate-this'
#| message: false

solution = pd.read_csv('data/milestone02.csv')
solution
```

Your task is to use what you've learned to transform `power` into this table.

You will need to create a new column called `percent_humidity` that contains values of percent humidity calculated according to the following formula:

**percent humidity = relative humidity / 100**

Work in the code chunk below.

```{python}
#| label: 'recreation-create'

```

#### Test it

Run the following code chunk to test whether your table has the same dimensions as the solution:

```{python}
#| label: 'compare_shape'

# The result will be `True` if the dimensions are the same
solution.shape == power.shape
```

Run the following code chunk to test whether your table matches the solution:

```{python}
#| label: 'compare'

# If your answer is correct, the comparison should return an empty DataFrame.
power.round(10).compare(solution.round(10))
```

### Part 3 - Visualize

Using the File Explorer on the left, navigate to the `images/` directory, then click on `milestone02.png` to open an image in the Editor pane

Your task is to recreate this plot using `power`.

Use the chunk below to recreate this plot.
**Hint:** Notice that the points are 50% transparent.
Be sure to check out the help documentation to see how this is done.

```{python}
#| label: 'recreation-visualize'

```

## Extension

Using the code chunk below, investigate a research question about this data, using the additional data wrangling skills you learned this week. Some ideas:

1. How does the daily temperature range (the difference between `t2m_max` and `t2m_min`) vary by month (or some other unit of time of interest)?
2. Based on your new `percent_humidity` variable, split the data into groups of your choosing (e.g. low/medium/high) and explore patterns based on these groups.
3. Is there a relationship between percent humidity and [another variable of your choosing]?
4. [any other research question of interest]

Alternately, working with a data set of your own, complete the following:

1. Read in your data
2. Create at least one new variable in your data set, or use other data wrangling tools to alter your data
3. Use your updated data set to create at least one graph and/or table

```{python}
#| label: 'extension'

```
