---
title: "Write functions"
format: html
---
# Instructions

This week, you learned how to write and apply your own functions.

You'll use these skills to add a column that matches month numbers (e.g., 1, 2, 3) to
their respective month names (e.g., January, February, March).

To learn more about the variables contained in the data set, refer to the data dictionary
[here](https://rstudio.github.io/academy-python-solar-power/assets/power_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None)
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off

```

## Write functions

As we work towards building polished reports and plots, it may be useful to
include month names in our data set rather than numbers.
In this milestone, you'll create a new variable that contains the month name that
is associated with each month number.

## Recreation

### Part 1 - Import

Before you begin, you will need to import your data set.
Use the code chunk below to read the data from the data file `power.csv`,
which is stored in the `data/` folder in your working directory.
Be sure to save the data set to a variable named `power`.

```{python}
#| label: 'recreation_import'

```

### Part 2 - Write a function

Your task is to write a function named `recode_month()` that will accept
an integer as input (e.g., `3`) and return the associated month name:

- 1: 'January'
- 2: 'February'
- 3: 'March'
- 4: 'April'
- 5: 'May'
- 6: 'June'
- 7: 'July'
- 8: 'August'
- 9: 'September'
- 10: 'October'
- 11: 'November'
- 12: 'December'

Don't worry about adding error checking for now (e.g., what if a number greater than 12 is input?).

```{python}
#| label: 'recreation-function'


```

#### Test it

Run the following code chunk to test your function on a few different values:

```{python}
#| label: 'compare_results'

recode_month(1) # should return 'January'
recode_month(3) # should return 'March'
recode_month(5) # should return 'May'
```

### Part 3 - Apply

Using your function, add a new column to `power` called `month`
that contains the name associated with each numeric month value (`mm`).
Then, save it as `data/power_with_months.csv`.
**Note:** when saving, set `index=False`.

```{python}
#| label: 'recreation_apply'

```

## Extension

Use the code chunk(s) below to investigate something about this data set using a function. You can use this as an opportunity to practice something we learned this week _or_ extend beyond that material - something that you can learn from experimentation, a help page, or a package website.

Consider:

1. Writing a function to perform a calculation involving one or more columns of the `power` data set
2. Writing a function that subsets the data set for a given time period (year, financial quarter, season?) and creates a visualization of the resulting data
3. Writing a function that creates a visualization of the data (possibly subsetted or grouped by time period) based on cardinal directions
4. [ something else that interests you ]

```{python}
#| label: 'extension'

```
